In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [2]:
import pandas as pd
import numpy as np

import seaborn as sns
import h5py

from numpy import loadtxt
from matplotlib import pyplot
from matplotlib import rcParams

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import classification_report, confusion_matrix
from keras.models import Sequential, model_from_json
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.metrics import accuracy_score, classification_report

### The data columns are:

1) Pregnancy
2) Glucose
3) Blood Pressure
4) SkinThickness
5) Insulin
6) BMI
7) DiabetesPedigreeFunction
8) Age
9) Outcome

We will be prediction column (9), whether the person has diabetes(1) or not(0).

## Loading dataset:

In [3]:
data = pd.read_csv('../data/diabetes.csv', header=None)

In [4]:
data.drop(0, inplace=True)
data

0    1   2   3    4     5      6   7  8
1     6  148  72  35    0  33.6  0.627  50  1
2     1   85  66  29    0  26.6  0.351  31  0
3     8  183  64   0    0  23.3  0.672  32  1
4     1   89  66  23   94  28.1  0.167  21  0
5     0  137  40  35  168  43.1  2.288  33  1
..   ..  ...  ..  ..  ...   ...    ...  .. ..
764  10  101  76  48  180  32.9  0.171  63  0
765   2  122  70  27    0  36.8   0.34  27  0
766   5  121  72  23  112  26.2  0.245  30  0
767   1  126  60   0    0  30.1  0.349  47  1
768   1   93  70  31    0  30.4  0.315  23  0

[768 rows x 9 columns]

In [5]:
data = data.to_numpy()
data

array([['6', '148', '72', ..., '0.627', '50', '1'],
       ['1', '85', '66', ..., '0.351', '31', '0'],
       ['8', '183', '64', ..., '0.672', '32', '1'],
       ...,
       ['5', '121', '72', ..., '0.245', '30', '0'],
       ['1', '126', '60', ..., '0.349', '47', '1'],
       ['1', '93', '70', ..., '0.315', '23', '0']], dtype=object)

In [6]:
X = data[:,0:8]
y = data[:, 8]

In [7]:
scaler = StandardScaler()

In [8]:
X_scaled = scaler.fit_transform(X)
print('X_scaled:\n', X_scaled)

X_scaled:
 [[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.8, random_state=42)

In [10]:
y_train = np_utils.to_categorical(y_train)

y_train

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.

In [11]:
print(type(X_train))
print(type(X_test))
print(type(y_train))
print(type(y_test))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


We'll be using the other columsn to predict feature 9: Diabetes diagnoses (0, 1) where 0 = No, 1 = Yes

In [12]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(2, input_dim=8, activation='sigmoid'))

## Compiling Keras Model

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])



In [14]:
model_fit = model.fit(X_train, y_train, validation_split=0.33, epochs=150, batch_size=10)



Epoch 1/150
11/11 [==============================] - 1s 17ms/step - loss: 0.7436 - accuracy: 0.5588 - val_loss: 0.7383 - val_accuracy: 0.5098
Epoch 2/150
11/11 [==============================] - 0s 4ms/step - loss: 0.7258 - accuracy: 0.5784 - val_loss: 0.7246 - val_accuracy: 0.5294
Epoch 3/150
11/11 [==============================] - 0s 3ms/step - loss: 0.7123 - accuracy: 0.6078 - val_loss: 0.7133 - val_accuracy: 0.5490
Epoch 4/150
11/11 [==============================] - 0s 5ms/step - loss: 0.7010 - accuracy: 0.6373 - val_loss: 0.7039 - val_accuracy: 0.5490
Epoch 5/150
11/11 [==============================] - 0s 4ms/step - loss: 0.6914 - accuracy: 0.6373 - val_loss: 0.6965 - val_accuracy: 0.5686
Epoch 6/150
11/11 [==============================] - 0s 4ms/step - loss: 0.6832 - accuracy: 0.6373 - val_loss: 0.6899 - val_accuracy: 0.5882
Epoch 7/150
11/11 [==============================] - 0s 4ms/step - loss: 0.6758 - accuracy: 0.6471 - val_loss: 0.6840 - val_accuracy: 0.5882
Epoch 8/150


Epoch 59/150
11/11 [==============================] - 0s 3ms/step - loss: 0.4146 - accuracy: 0.8137 - val_loss: 0.5555 - val_accuracy: 0.7451
Epoch 60/150
11/11 [==============================] - 0s 3ms/step - loss: 0.4105 - accuracy: 0.8137 - val_loss: 0.5560 - val_accuracy: 0.7451
Epoch 61/150
11/11 [==============================] - 0s 4ms/step - loss: 0.4079 - accuracy: 0.8137 - val_loss: 0.5577 - val_accuracy: 0.7451
Epoch 62/150
11/11 [==============================] - 0s 3ms/step - loss: 0.4046 - accuracy: 0.8137 - val_loss: 0.5606 - val_accuracy: 0.7451
Epoch 63/150
11/11 [==============================] - 0s 4ms/step - loss: 0.4012 - accuracy: 0.8137 - val_loss: 0.5626 - val_accuracy: 0.7451
Epoch 64/150
11/11 [==============================] - 0s 4ms/step - loss: 0.3985 - accuracy: 0.8137 - val_loss: 0.5616 - val_accuracy: 0.7451
Epoch 65/150
11/11 [==============================] - 0s 3ms/step - loss: 0.3955 - accuracy: 0.8235 - val_loss: 0.5576 - val_accuracy: 0.7451
Epoch 

11/11 [==============================] - 0s 4ms/step - loss: 0.2939 - accuracy: 0.8824 - val_loss: 0.6158 - val_accuracy: 0.7451
Epoch 117/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2927 - accuracy: 0.8922 - val_loss: 0.6153 - val_accuracy: 0.7451
Epoch 118/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2907 - accuracy: 0.8922 - val_loss: 0.6189 - val_accuracy: 0.7451
Epoch 119/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2891 - accuracy: 0.8922 - val_loss: 0.6211 - val_accuracy: 0.7451
Epoch 120/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2901 - accuracy: 0.8922 - val_loss: 0.6199 - val_accuracy: 0.7451
Epoch 121/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2869 - accuracy: 0.8922 - val_loss: 0.6221 - val_accuracy: 0.7451
Epoch 122/150
11/11 [==============================] - 0s 3ms/step - loss: 0.2854 - accuracy: 0.8922 - val_loss: 0.6234 - val_accuracy: 0.7451
Epoch 123/150

## Evaluating the model

In [15]:
_, accuracy = model.evaluate(X_train, y_train)
print(accuracy*100)

5/5 [==============================] - 0s 2ms/step - loss: 0.3891 - accuracy: 0.8562
85.62091588973999


In [16]:
print(type(accuracy))
print(type(_))

<class 'float'>
<class 'float'>


## Predictions

In [17]:
predictions = np.argmax(model.predict(X_test), axis=1)
for i in range(10):
    print(X_test[i].tolist(), predictions[i], y[i])
    
    
    

20/20 [==============================] - 0s 850us/step
[0.6399472601593604, -0.7165334717264664, -0.5741277459136239, 0.7818138030884986, 0.9568596530309466, 0.2547804694892914, -0.12647140206047627, 0.8303811324799334] 0 1
[-0.5479185907225461, -0.2783734371474431, 0.30473400231574344, 0.7190857419965673, -0.6928905722954675, 0.4705431865971717, -0.9781448690748651, -1.0415494364835023] 0 0
[-0.5479185907225461, -0.4035620184557355, -0.2639412465385531, -1.2882122129452358, -0.6928905722954675, -0.1513611156549531, -0.9479436823013052, -1.0415494364835023] 0 1
[1.2338801856003137, -0.4348591637828086, 0.5632227517949692, -1.2882122129452358, -0.6928905722954675, -0.938260436871927, 1.160099154493175, 0.06459135426761875] 0 0
[0.9369137228798371, 0.4727580507023112, 1.0802002507534205, -1.2882122129452358, -0.6928905722954675, -0.26558843647677216, -0.7908975110787937, 1.4259954044228447] 1 1
[0.6399472601593604, -0.560047745091101, 0.149640752628208, 0.7190857419965673, 0.956859653030

In [18]:
type(predictions)

numpy.ndarray

In [19]:
print(type(X_test))

<class 'numpy.ndarray'>


In [20]:
y_pred = model.predict(X_test)
y_pred

20/20 [==============================] - 0s 919us/step


array([[0.6012138 , 0.33926383],
       [0.97549105, 0.03605298],
       [0.92440337, 0.10895424],
       ...,
       [0.49479282, 0.48594034],
       [0.89102083, 0.14259213],
       [0.09416676, 0.89994365]], dtype=float32)

In [21]:
y_pred = np.where(y_pred > 0.5, 1, 0)

In [22]:
y_pred

array([[1, 0],
       [1, 0],
       [1, 0],
       ...,
       [0, 0],
       [1, 0],
       [0, 1]])

In [23]:
y_pred = np.argmax(y_pred, axis=1)

In [24]:
accuracy_score(y_test, y_pred)

TypeError: Labels in y_true and y_pred should be of the same type. Got y_true=['0' '1'] and y_pred=[0 1]. Make sure that the predictions provided by the classifier coincides with the true labels.